apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    {{- include "ai-todo.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.backend.type }}
  ports:
  - port: {{ .Values.service.backend.port }}
    targetPort: {{ .Values.service.backend.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "ai-todo.backend.selectorLabels" . | nindent 4 }}
