apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.clusterName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: kafka-cluster
spec:
  kafka:
    version: {{ .Values.kafka.version }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: {{ .Values.kafka.replicationFactor }}
      transaction.state.log.replication.factor: {{ .Values.kafka.replicationFactor }}
      transaction.state.log.min.isr: {{ .Values.kafka.minInsyncReplicas }}
      default.replication.factor: {{ .Values.kafka.replicationFactor }}
      min.insync.replicas: {{ .Values.kafka.minInsyncReplicas }}
      log.retention.hours: {{ .Values.kafka.defaultRetentionHours }}
    jvmOptions:
      -Xms: {{ .Values.kafka.jvm.heapMin }}
      -Xmx: {{ .Values.kafka.jvm.heapMax }}
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
    userOperator:
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
