#!/bin/bash
# Build Docker images for AI Todo application
# Generated by Claude Code for Phase 6 (User Story 4 - Automation)

set -e  # Exit on any error

echo "=========================================="
echo "Building AI Todo Docker Images"
echo "=========================================="
echo ""

# Configuration
FRONTEND_IMAGE="ai-todo-frontend:v1.0.0"
BACKEND_IMAGE="ai-todo-backend:v1.0.0"
TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")

echo "[$TIMESTAMP] Starting image builds..."
echo ""

# Build frontend image
echo "Building frontend image: $FRONTEND_IMAGE"
cd frontend
docker build -t $FRONTEND_IMAGE . || {
    echo "ERROR: Frontend image build failed"
    exit 1
}
cd ..
echo "✓ Frontend image built successfully"
echo ""

# Build backend image
echo "Building backend image: $BACKEND_IMAGE"
cd backend
docker build -t $BACKEND_IMAGE . || {
    echo "ERROR: Backend image build failed"
    exit 1
}
cd ..
echo "✓ Backend image built successfully"
echo ""

# Verify images
echo "Verifying images..."
docker images | grep ai-todo
echo ""

# Check image sizes
FRONTEND_SIZE=$(docker images $FRONTEND_IMAGE --format "{{.Size}}")
BACKEND_SIZE=$(docker images $BACKEND_IMAGE --format "{{.Size}}")

echo "Image sizes:"
echo "  Frontend: $FRONTEND_SIZE (target: <500MB)"
echo "  Backend: $BACKEND_SIZE (target: <300MB)"
echo ""

echo "=========================================="
echo "Build completed successfully!"
echo "=========================================="
echo ""
echo "Next steps:"
echo "  1. Run ./scripts/load-images.sh to load images into Minikube"
echo "  2. Run ./scripts/deploy.sh to deploy to Kubernetes"
