#!/bin/bash
# Cleanup script for AI Todo deployment
# Generated by Claude Code for Phase 7 (Polish)

set -e  # Exit on any error

echo "=========================================="
echo "AI Todo Cleanup"
echo "=========================================="
echo ""

RELEASE_NAME="ai-todo"
NAMESPACE=${1:-default}

echo "This will remove:"
echo "  - Helm release: $RELEASE_NAME"
echo "  - Kubernetes resources in namespace: $NAMESPACE"
echo ""
read -p "Are you sure? (yes/no): " CONFIRM

if [ "$CONFIRM" != "yes" ]; then
    echo "Cleanup cancelled"
    exit 0
fi

echo ""
echo "Uninstalling Helm release..."
helm uninstall $RELEASE_NAME -n $NAMESPACE || {
    echo "WARNING: Helm uninstall failed or release not found"
}

echo ""
echo "Cleaning up remaining resources..."
kubectl delete configmap -n $NAMESPACE -l app.kubernetes.io/part-of=ai-todo || true
kubectl delete secret -n $NAMESPACE -l app.kubernetes.io/part-of=ai-todo || true

echo ""
echo "Verifying cleanup..."
kubectl get all -n $NAMESPACE -l app.kubernetes.io/part-of=ai-todo

echo ""
echo "=========================================="
echo "Cleanup completed!"
echo "=========================================="
echo ""
echo "Note: Docker images are still present locally"
echo "To remove images:"
echo "  docker rmi ai-todo-frontend:v1.0.0"
echo "  docker rmi ai-todo-backend:v1.0.0"
