./scripts/deploy.sh#!/bin/bash
# Master deployment script for AI Todo application
# Generated by Claude Code for Phase 6 (User Story 4 - Automation)
# Automates: build → load → deploy workflow

set -e  # Exit on any error

echo "=========================================="
echo "AI Todo Automated Deployment"
echo "=========================================="
echo ""

# Configuration
RELEASE_NAME="ai-todo"
NAMESPACE="default"
CHART_PATH="./charts/ai-todo"
TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
LOG_FILE="deploy-$(date +%Y%m%d-%H%M%S).log"

# Redirect output to both console and log file
exec > >(tee -a "$LOG_FILE")
exec 2>&1

echo "[$TIMESTAMP] Starting automated deployment..."
echo "Release: $RELEASE_NAME"
echo "Namespace: $NAMESPACE"
echo "Chart: $CHART_PATH"
echo "Log file: $LOG_FILE"
echo ""

# Step 1: Build Docker images
echo "=========================================="
echo "Step 1: Building Docker images"
echo "=========================================="
./scripts/build-images.sh || {
    echo "ERROR: Image build failed"
    exit 1
}
echo ""

# Step 2: Load images into Minikube
echo "=========================================="
echo "Step 2: Loading images into Minikube"
echo "=========================================="
./scripts/load-images.sh || {
    echo "ERROR: Image loading failed"
    exit 1
}
echo ""

# Step 3: Deploy with Helm
echo "=========================================="
echo "Step 3: Deploying with Helm"
echo "=========================================="

# Check if release already exists
if helm list -n $NAMESPACE | grep -q $RELEASE_NAME; then
    echo "Release $RELEASE_NAME already exists. Upgrading..."
    helm upgrade $RELEASE_NAME $CHART_PATH \
        --namespace $NAMESPACE \
        --wait \
        --timeout 5m || {
        echo "ERROR: Helm upgrade failed"
        echo "Rolling back to previous version..."
        helm rollback $RELEASE_NAME -n $NAMESPACE
        exit 1
    }
    echo "✓ Helm upgrade completed"
else
    echo "Installing new release: $RELEASE_NAME"
    helm install $RELEASE_NAME $CHART_PATH \
        --namespace $NAMESPACE \
        --create-namespace \
        --wait \
        --timeout 5m || {
        echo "ERROR: Helm install failed"
        exit 1
    }
    echo "✓ Helm install completed"
fi
echo ""

# Step 4: Health check
echo "=========================================="
echo "Step 4: Running health checks"
echo "=========================================="
./scripts/health-check.sh $NAMESPACE || {
    echo "ERROR: Health check failed"
    echo "Check pod logs with: kubectl logs -l app.kubernetes.io/part-of=ai-todo -n $NAMESPACE"
    exit 1
}
echo ""

# Deployment summary
DEPLOYMENT_TIME=$((SECONDS / 60))
echo "=========================================="
echo "Deployment Summary"
echo "=========================================="
echo "Status: SUCCESS"
echo "Release: $RELEASE_NAME"
echo "Namespace: $NAMESPACE"
echo "Deployment time: ${DEPLOYMENT_TIME} minutes"
echo "Log file: $LOG_FILE"
echo ""
echo "To check status:"
echo "  kubectl get pods -n $NAMESPACE"
echo "  kubectl get services -n $NAMESPACE"
echo ""
echo "To view logs:"
echo "  kubectl logs -l app.kubernetes.io/component=frontend -n $NAMESPACE"
echo "  kubectl logs -l app.kubernetes.io/component=backend -n $NAMESPACE"
echo ""
echo "To uninstall:"
echo "  helm uninstall $RELEASE_NAME -n $NAMESPACE"
echo ""
echo "=========================================="
echo "Deployment completed successfully!"
echo "=========================================="
