#!/bin/bash
# Health check for deployed application
# Generated by Claude Code for Phase 6 (User Story 4 - Automation)

set -e  # Exit on any error

echo "=========================================="
echo "AI Todo Health Check"
echo "=========================================="
echo ""

NAMESPACE=${1:-default}
TIMEOUT=120  # 2 minutes timeout

echo "Checking deployment in namespace: $NAMESPACE"
echo ""

# Check if pods are running
echo "Checking pod status..."
kubectl get pods -n $NAMESPACE -l app.kubernetes.io/part-of=ai-todo

# Wait for pods to be ready
echo ""
echo "Waiting for pods to be ready (timeout: ${TIMEOUT}s)..."
kubectl wait --for=condition=ready pod \
    -l app.kubernetes.io/part-of=ai-todo \
    -n $NAMESPACE \
    --timeout=${TIMEOUT}s || {
    echo "ERROR: Pods did not become ready within timeout"
    echo ""
    echo "Pod details:"
    kubectl describe pods -n $NAMESPACE -l app.kubernetes.io/part-of=ai-todo
    exit 1
}

echo "✓ All pods are ready"
echo ""

# Check services
echo "Checking services..."
kubectl get services -n $NAMESPACE -l app.kubernetes.io/part-of=ai-todo
echo ""

# Check endpoints
echo "Checking service endpoints..."
kubectl get endpoints -n $NAMESPACE
echo ""

# Get frontend access information
echo "=========================================="
echo "Application Access Information"
echo "=========================================="
echo ""

FRONTEND_SERVICE=$(kubectl get service -n $NAMESPACE -l app.kubernetes.io/component=frontend -o jsonpath='{.items[0].metadata.name}')
SERVICE_TYPE=$(kubectl get service $FRONTEND_SERVICE -n $NAMESPACE -o jsonpath='{.spec.type}')

if [ "$SERVICE_TYPE" == "NodePort" ]; then
    MINIKUBE_IP=$(minikube ip)
    NODE_PORT=$(kubectl get service $FRONTEND_SERVICE -n $NAMESPACE -o jsonpath='{.spec.ports[0].nodePort}')
    echo "Access the application at: http://$MINIKUBE_IP:$NODE_PORT"
elif [ "$SERVICE_TYPE" == "LoadBalancer" ]; then
    echo "Service type: LoadBalancer"
    echo "Run 'minikube tunnel' in a separate terminal, then access at: http://localhost:80"
else
    echo "Service type: $SERVICE_TYPE"
    echo "Use port-forward: kubectl port-forward service/$FRONTEND_SERVICE 3000:80"
fi

echo ""
echo "=========================================="
echo "Health check completed successfully!"
echo "=========================================="
