#!/bin/bash
# Load Docker images into Minikube
# Generated by Claude Code for Phase 6 (User Story 4 - Automation)

set -e  # Exit on any error

echo "=========================================="
echo "Loading Images into Minikube"
echo "=========================================="
echo ""

# Configuration
FRONTEND_IMAGE="ai-todo-frontend:v1.0.0"
BACKEND_IMAGE="ai-todo-backend:v1.0.0"
TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")

# Check if Minikube is running
echo "[$TIMESTAMP] Checking Minikube status..."
if ! minikube status &> /dev/null; then
    echo "ERROR: Minikube is not running"
    echo "Please start Minikube with: minikube start --driver=docker"
    exit 1
fi
echo "✓ Minikube is running"
echo ""

# Load frontend image
echo "Loading frontend image: $FRONTEND_IMAGE"
minikube image load $FRONTEND_IMAGE || {
    echo "ERROR: Failed to load frontend image"
    exit 1
}
echo "✓ Frontend image loaded"
echo ""

# Load backend image
echo "Loading backend image: $BACKEND_IMAGE"
minikube image load $BACKEND_IMAGE || {
    echo "ERROR: Failed to load backend image"
    exit 1
}
echo "✓ Backend image loaded"
echo ""

# Verify images in Minikube
echo "Verifying images in Minikube..."
minikube image ls | grep ai-todo
echo ""

echo "=========================================="
echo "Images loaded successfully!"
echo "=========================================="
echo ""
echo "Next steps:"
echo "  1. Run ./scripts/deploy.sh to deploy to Kubernetes"
