apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: dapr-secretstore
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: kubernetes-secretstore
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []
    # No additional metadata required for Kubernetes secret store
    # It automatically uses the service account's permissions
